### ISSUE TITLE
Is it possible to register Shotcut as a "verified app" on Flathub?

### ISSUE THREAD

**Issue by marco4mp** [flathub/org.shotcut.Shotcut#100]
Hi. It is a request as a question because I do not know if there will be any impediment.

**Comment by ddennedy** [comment]
I just did this and completed the verification step in the Flathub portal. Just waiting for the website to update; seems there might be a publish or cache delay
```
$ curl https://shotcut.org/.well-known/org.flathub.VerifiedApps.txt
b745abbb-3603-48af-a438-e8a304fb6cea
```

**Comment by hfiguiere** [comment]
![image](https://github.com/flathub/org.shotcut.Shotcut/assets/114441/ed990772-cb09-4240-98f4-071027b84209)
