### ISSUE TITLE
Shotcut is using deprecated org.freedesktop.Platform.GL

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.shotcut.Shotcut#117]
I have two installations of Shotcut as flatpak and they are referencing EOL'd runtime components:

fedora Silverblue 41 Beta:
org.freedesktop.LinuxAudio.Plugins.swh/x86_64/22.08

fedora Worksation 40 Cinnamon spin:
org.freedesktop.LinuxAudio.Plugins.swh/x86_64/22.08
org.freedesktop.Platform.GL.default/x86_64/22.08
org.freedesktop.Platform.GL.default/x86_64/22.08-extra

The application runtime itself has been kept current but these helper runtimes are lagging behind.

**Comment by ddennedy** [comment]
Can you submit a PR for it?

**Comment by neildarlow** [comment]
Hi Dan,

I'm a casual user. I can see the runtime versions for org.freedesktop.LinuxAudio.Plugins(.swh) in org.shotcut.Shotcut.yaml.

If that just needs updating to e.g. 24.08 then I could maybe clone, modify, edit and issue a PR but I've never built Shotcut before.

I don't see where the GL.default stuff came in unless it gets pulled-in with the base runtime.

Regards,
Neil Darlow

On 22 October 2024 17:57:49 BST, Dan Dennedy ***@***.***> wrote:
>Can you submit a PR for it?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/flathub/org.shotcut.Shotcut/issues/117#issuecomment-2429797282
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail.

**Comment by ddennedy** [comment]
LADSPA is fixed in the beta. Release is going to wait until beta is done by end of October.

**Comment by ddennedy** [comment]
When installing the draft build for the new release today, I see it fixed the indirect components:
```
 1. [✓] org.freedesktop.Platform.GL.default 23.08       u  flathub         2.0 kB / 163.9 MB
 2. [✓] org.freedesktop.Platform.GL.default 23.08-extra u  flathub         1.9 kB / 163.9 MB
```
