### ISSUE TITLE
Shotcut remain active even after close it for long time !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.shotcut.Shotcut#14]
Hi. I was using Shotcut from RPMFusion repositories for years without problem on my Fedora.
2 days ago, I remove .rpm package & installed this flatpak package.

1st thing I noticed, was that my laptop boot time last longer on next boot ! But subsequently - on next booting trails - disappear.

2nd note, I noticed that the fan of my laptop started to work more frequently - even without launching shotcut !

3rd: today, I used shotcut to convert mkv file 27 MB to MP4. It took about 20 minutes to complete (& failed on 1st trail: reach to 84% then I received system message said there is error ....). I closed program (force close), then I finish conversion after 2nd trail. Then I close shotcut. After that I used laptop in other works for about 4 hrs. After finishing my work I shutdown PC, but it remain long time on logout screen ! I press "Esc" to see what was going: I saw at button what mean:
"systemd try to kill process ... shotcut"

There is(are) something(s) abnormal in this flatpak package & I'm now thinking to remove it & return to .rpm package which has same version but has no such behaviour ! How shotcut (flatpak-shotcut) remain active in background in-spite of closing it ?!!

Please your kind attention for this strange issue !

**Comment by Nokia808** [comment]
Hi again. I can now confirm this bug 100%. I removed flatpak package & re-installed .rpm package & perform same step & I did not face any errors. This flatpak package need re-work & fix.

**Comment by eszlari** [comment]
This doesn't seem to be a Shotcut specific bug, but Flatpak or Fedora related, so please file a bug report on their bug trackers:

Flatpak: https://github.com/flatpak/flatpak/issues
Fedora: https://bugzilla.redhat.com/
