### ISSUE TITLE
Is this permission for "canonical" normal to appear in flatpak package?!

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.shotcut.Shotcut#15]
I noticed during installation this flatpak package that it need permission for what mean:

"Canonical Application menu register"

I do not remember it exactly but I'm sure about canonical !!

What is the relation of canonical to this application ? Can you kindly explain. I'm suspicious about this specially with taking in mind issue https://github.com/flathub/org.shotcut.Shotcut/issues/14

**Comment by Nokia808** [comment]
Hi. This permission for "canonical ......" is for snap package only NOT FOR FLATPAK !!
Why this permission, which has logical place in snap, appearing here in flatpak ?
Please correct this.

**Comment by TingPing** [comment]
It has nothing to do with snap. Ubuntu made support for global menus back in Unity that Qt uses.

I have no idea if its still relevant but thats a permission from the KDE runtime not this application anyway.
