### ISSUE TITLE
Make the short description more straight to the point

### ISSUE THREAD

**Issue by trosh** [flathub/org.shotcut.Shotcut#2]
On https://flathub.org/home, there is a link to Shotcut with its short description truncated. The complete short description is

> A free, open source, cross-platform **video editor**

but once truncated it shows up as

> A free, open source, cross-platfo...

I saw this and had no idea what this was for (the icon doesn't help much when you don't know what you're looking at).

I suggest changing the short description to something like

> Video editor (FOSS, x-platform)

Alternately improve the flathub homepage to display the whole description as alt text, and/or display metadata like FOSS/platforms appear as a sub-icon or something else standardized.

**Comment by eszlari** [comment]
This has been fixed now with version 18.06.01.
