### ISSUE TITLE
How do you install plugins?

### ISSUE THREAD

**Issue by jcc10** [flathub/org.shotcut.Shotcut#28]
I am trying to install this plugin for use with my 360 footage. I was wondering how to install it with a flatpak install.

BTW: the bitbucket repo has more info on how to set it up.

**Comment by ddennedy** [comment]
FYI, this is reference to the bigsh0t frei0r plugins at https://bitbucket.org/leo_sutic/bigsh0t/src/master/
This repo's CMakeLists.txt does not have an install target. You can use `install` to install the built `.so` files to the target install directory + `lib/frei0r-1/`. You do not need to worry about installing the generated `.qml` UI files; these are already included in Shotcut where they are improved and translated.

**Comment by ddennedy** [comment]
confirmed
