### ISSUE TITLE
Can this be regularly updated please?

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.shotcut.Shotcut#39]
Hi,

The last update to 21.05.x was done via a pull-request. Can regular updates be handled by a bot-build maybe? 21.06.29 has been released.

ATB,
Neil

**Comment by hfiguiere** [comment]
you can submit PR too.

**Comment by neildarlow** [comment]
Hi @hfiguiere,

I wasn't being lazy or rude. I was simply suggesting that automated updates might be the way to go rather than relying on pull-requests.

ATB,
Neil

**Comment by ddennedy** [comment]
Sorry, I am upstream lead developer and helping to maintain this now as of version 21.05.28. I do not think there is a way to automatic this; rather, I need to add this to my checklist.
This flatpak is updated now in b53616bfaf46277a56cb3dffce1247aa12a6fe6e. Please allow a day for the flathub publishing process.

**Comment by neildarlow** [comment]
Hi @ddennedy,

Thank you for your work on Shotcut. It's greatly appreciated.

I only posted because I've seen flatpaks being pushed-out by buildbots and thought that might help for routine updates where no changes to dependencies are involved.

ATB,
Neil

**Comment by hfiguiere** [comment]
thing is (I'm not this repo maintainer) I didn't have this app on my (ever growing) watch list. I was about to get to it this evening. thanks @ddennedy for taking care of it.

**Comment by neildarlow** [comment]
@hfiguiere,

Exactly, and my wish was to see some sort of automation to reduce the workload of the flathub team. There will come a time that the number of applications on flathub will make manual updating very challenging.

The work you do in curating all of these applications is incredible. I see the quality of the packages improving all the time and it would be a pity to see any of you struggle because of your workload.

ATB,
Neil
