### ISSUE TITLE
 org.kde.Platform//5.15 is end-of-life

### ISSUE THREAD

**Issue by timlau** [flathub/org.shotcut.Shotcut#55]
Not a big issue, but it looks like the 5.15 is just marked EOL and have not received any updates for a long time
looks like 5.15-21.08 is the only 5.xx branch there is getting any updates

As shotcut work fine with the 5.15-21.08 it would properly be a good idea to use that,

https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/32

```bash
 flatpak update
Looking for updates…
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.shotcut.Shotcut
Nothing to do.

```

**Comment by ddennedy** [comment]
What does "21.08" mean in the context of the flatpak ecosystem? I tried searching and I see some other runtimes such as FreeDesktop that have this version. Does it require a certain version of a daemon or library to launch the flatpak? What about the LADSPA plugin flatpaks Shotcut is using?

**Comment by ddennedy** [comment]
See https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension#runtime-considerations
"Plugins and applications have to use the same runtime" OK, the flatpak ecosystem is starting to resemble yet another coordinated packaging system. I see 21.08 branches for these plugins.

**Comment by hfiguiere** [comment]
> What does "21.08" mean in the context of the flatpak ecosystem? 

Mean it's the KDE 5.15 runtime rebased on the freedsktop 21.08 runtime.
