### ISSUE TITLE
shotcut's export does not have libx265 option through flatpak

### ISSUE THREAD

**Issue by dim-geo** [flathub/org.shotcut.Shotcut#6]
Hi,

export in shotcut through flatpak does not have x265 option
Please check the [issue](https://github.com/mltframework/shotcut/issues/603) that  I have raised in shotcut.

**Comment by eszlari** [comment]
Support for x265 could certainly added, but is it really a relevant/useful format?

**Comment by dim-geo** [comment]
I think yes.
I want it so I can share some intermediate montages with friends. It has
excellent quality per size.
Shotcut advertises x265 support in a YouTube video.
Also x265 is the future 😉

Στις Τρί, 26 Ιουν 2018, 03:43 ο χρήστης eszlari <notifications@github.com>
έγραψε:

**Comment by AsciiWolf** [comment]
Yup, x265 should definitely be added.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.shotcut.Shotcut/commit/412fa703ca8440731c7607f0d7132918a5005542
