### ISSUE TITLE
Add --socket=wayland

### ISSUE THREAD

**Issue by grulja** [flathub/org.shotcut.Shotcut#7]
Shotcut is not able to run under Wayland if **--socket=wayland** is not used.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.shotcut.Shotcut/commit/2d51d8229d12b1310790d9c583f757a39b3fc7b5

Strange. This worked for me without `--socket=wayland` in a Plasma 5.14 Wayland session inside a VM.

**Comment by Jmennius** [comment]
I guess because of #19 this has to be reopened.
Wayland works perfectly fine if you allow socket access.
In case wayland doesn't work for somebody - we can provide instructions on how to make application use XWayland (`QT_QPA_PLATFORM=xcb`)

**Comment by ddennedy** [comment]
@Jmennius see build to test in PR #41
