### ISSUE TITLE
No such filter: 'zscale'

### ISSUE THREAD

**Issue by rnsag22** [flathub/org.shotcut.Shotcut#75]
Hi,

Installed Shotcut from Flathub.org. Tried the current stable version and the beta version as well. Running into the same issue with both.
I am loading a video file and Shotcut offers me to 'Convert to edit-friendly...'.

Once I choose that, the job starts but immediately errors out.

See the log below:

> ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/app --enable-rpath --enable-gpl --enable-version3 --disable-static --enable-shared --disable-doc --disable-alsa --enable-libfontconfig --enable-libfreetype --enable-libopus --enable-libpulse --enable-librsvg --enable-libvpx --enable-libdav1d --enable-libxml2 --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libtheora --enable-libvmaf --enable-libvorbis --enable-libwebp --enable-libaom --disable-decoder=libaom_av1 --enable-nvenc --enable-vaapi
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[h264 @ 0x5623de17da80] Reinit context to 3344x2352, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/111/Kooha-2023-04-07-16-21-35.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2023-04-07T14:21:35.000000Z
    encoder         : x264
  Duration: 00:44:57.58, start: 0.000000, bitrate: 1846 kb/s
  Stream #0:0[0x1](und): Video: h264 (Constrained Baseline), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-1, progressive, left), 3336x2346 (3344x2352) [SAR 1:1 DAR 556:391], 1847 kb/s, 40 fps, 40 tbr, 4k tbn (default)
    Metadata:
      creation_time   : 2023-04-07T14:21:35.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: mp3 (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 32 kb/s (default)
    Metadata:
      creation_time   : 2023-04-07T14:21:35.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> utvideo (native))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> pcm_f32le (native))
Press [q] to stop, [?] for help
[h264 @ 0x5623de199b40] Reinit context to 3344x2352, pix_fmt: yuv420p
[graph_1_in_0_1 @ 0x5623e0f54d40] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:mono
[format_out_0_1 @ 0x5623e0f55800] auto-inserting filter 'auto_aresample_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_1'
[auto_aresample_0 @ 0x5623e0f56b40] ch:1 chl:mono fmt:fltp r:48000Hz -> ch:1 chl:mono fmt:flt r:48000Hz
[AVFilterGraph @ 0x5623e1e685c0] No such filter: 'zscale'
Error reinitializing filters!
Failed to inject frame into filter network: Filter not found
Error while processing the decoded data for stream #0:0
[AVIOContext @ 0x5623de182840] Statistics: 0 bytes written, 0 seeks, 0 writeouts
Terminating demuxer thread 0
[AVIOContext @ 0x5623de184e80] Statistics: 2863929 bytes read, 2 seeks
Conversion failed!
Failed with exit code 1

I cannot offer a sample video but I can tell you that the video was created with Kooha and saved as an mp4-file. Maybe you can look into it.

![1](https://user-images.githubusercontent.com/130372708/230939524-44f4cfea-8854-45b5-8d4a-c94ab6157032.png)

**Comment by ddennedy** [comment]
Thanks for the notice. I am working on adding the zimg dependency for the zscale filter, but it is probably OK to cancel this dialog and use the file as-is. This is mainly for HDR or really obscure sources.

**Comment by ddennedy** [comment]
I made a new stable (22.12) build, which should be published tomorrow.
