### ISSUE TITLE
runtime org.kde.Platform 6.4 is end-of-life

### ISSUE THREAD

**Issue by callegar** [flathub/org.shotcut.Shotcut#85]
I believe this is because the runtime is actually QT 6.4 for which security support has ended 5 months ago. Wonder if Shotcut might build cleanly with 6.5.

**Comment by ddennedy** [comment]
Yes, it should compile fine on that. However, I do not like to change the runtime of an existing release. I will do it for the next release, which is due by the end of September.

**Comment by callegar** [comment]
Thanks!

**Comment by callegar** [comment]
Thanks!

**Comment by callegar** [comment]
Thanks!

**Comment by ddennedy** [comment]
unfortunately build fails on Qt 6.5 within glaxnimate module:
https://buildbot.flathub.org/#/builders/7/builds/7745

**Comment by ddennedy** [comment]
A new version of Glaxnimate was released that supports Qt 6.5. See PR #87. So, this is back on for the next beta and release.

**Comment by AsciiWolf** [comment]
It looks like that Shotcut now uses the 6.5 runtime.
